name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: ports-tool
            asset_name: ports-tool-linux-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: ports-tool.exe
            asset_name: ports-tool-windows-x86_64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: ports-tool
            asset_name: ports-tool-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: ports-tool
            asset_name: ports-tool-macos-aarch64

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Rename artifacts for release
      run: |
        mv ports-tool-linux-x86_64/ports-tool ports-tool-linux-x86_64
        mv ports-tool-windows-x86_64.exe/ports-tool.exe ports-tool-windows-x86_64.exe
        mv ports-tool-macos-x86_64/ports-tool ports-tool-macos-x86_64
        mv ports-tool-macos-aarch64/ports-tool ports-tool-macos-aarch64
        # Create a generic Linux binary as 'ports-tool' for easy installation
        cp ports-tool-linux-x86_64 ports-tool
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ports-tool-linux-x86_64
          ports-tool-windows-x86_64.exe
          ports-tool-macos-x86_64
          ports-tool-macos-aarch64
          ports-tool
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}