name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Build
      run: cargo build --release
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ports-tool-linux-x86_64
        path: target/release/ports-tool

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Prepare release assets
      run: |
        # Debug: list directory structure
        ls -la
        ls -la ports-tool-linux-x86_64/
        # Copy the binary with a descriptive name
        cp ports-tool-linux-x86_64/ports-tool ./ports-tool-linux
        # Create a generic binary as 'ports-tool' for easy installation
        cp ports-tool-linux-x86_64/ports-tool ./ports-tool
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ports-tool-linux
          ports-tool
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}